version: "3.9"
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ticketa
      POSTGRES_USER: ticketa
      POSTGRES_PASSWORD: ticketa
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
  adminer:
    image: adminer:4
    ports:
      - "8080:8080"
volumes:
  dbdata:
